# Generated by Django 4.1 on 2022-08-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="images/default.jpg",
                help_text="Upload a product image",
                upload_to="images/",
                verbose_name="image",
            ),
        ),
    ]
